### ISSUE TITLE
gpu.drawLine coordinates are not 1-based

### ISSUE THREAD

**Issue by wh0vian79** [Capy64/Capy64#11]
**Side**
- [ ] Lua side
- [ ] C# side
- [ ] Other
- [X] I don't know

**Describe the bug**
the drawRectangle works as if top,left is 1,1 and drawLine seems to think it's 0,0 (maybe?)

**To Reproduce**
1. gpu.drawRectangle(1, 1, 10, 10, 0xf0f0f0, 1)
2. gpu.drawLine(1, 1, 10, 1, 0xff00ff, 1)
3. the pink line skips the first pixel

also gpu.setSize(width, height) doesn't want to work... in the lua console gpu.setSize(320, 200) just returns "false" and is ignored in my .lua scripts.

other than that it's quite fun to play with =oD

**Expected behavior**
![Capy64_1-0-0-beta-bug](https://user-images.githubusercontent.com/60309074/226609995-239242f3-a99d-44d1-b399-4cdc35789cce.png)

**Screenshots**
https://drive.google.com/file/d/1QqZGjJURalmwXRGJsTJgfzclTUNYqllv/view?usp=share_link

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version: [e.g. 22]
 - Capy64 Version: [e.g. 0.0.9-alpha]

**Additional context**

**Comment by Ale32bit** [comment]
Hi, thanks for reporting this issue!

I will look into `gpu.drawLine`, normally every coordinate should be 1-based, like `gpu.drawRectangle`.

Regarding `gpu.setSize`, this is normal behaviour yet to be documented (I am working on redoing the entire documentation).

Since 0.0.10-alpha I added "classic" and "free" modes, classic mode has a fixed window size that cannot be changed and the Lua tickrate is set to 20 (20 updates per second).
Free mode allows `gpu.setSize` and manual resizing of the window, and the tickrate is set to 60.

The mode can be changed by setting "engineMode" to `0` or `1`, respectively "classic" and "free", the settings file can be found in `%APPDATA%/Capy64/settings.json`.
